# The config of the PetDragon plugin
# Created by 3ricL, minecraft name: Ericdebouwer
# -
# Edit this configuration with care, and NEVER use tabs!
# If this configuration breaks, my plugin will try to explain what should be changed/fixed
# to reset it, simply remove it from the "PetDragon" folder and it will generate a new one
# -
# You can use color codes in the messages by using the §-symbol,
# as seen on: https://www.digminecraft.com/lists/color_list_pc.php
###################################################################

plugin-prefix: "§r[§5§lPetDragon§r] "

# whether the plugin will check for updates on start-up
check-for-updates: true

# Whether or not using a mouse button with empty hand allows you to ride a dragon
# Both can be enabled at the same time
right-click-to-ride: true
left-click-to-ride: true

# Whether PetDragons destroy blocks in their path like a normal enderdragon does
do-block-destruction: true

# Whether a PetDragon can fly through blocks at all!
# If set to 'false' it will still break some blocks, see the option above to disable that
fly-through-blocks: true

# If a PetDragon will damage other entities when flying through them (fireballs will work regardless)
# Those entities will still be launched away, see option below
do-entity-damage: true

# If a PetDragon should interact at all with other entities (swoop them away)
# if set to 'false' PetDragons will also NOT damage other entities
do-entity-interact: true

# Whether or not a PetDragon will show the enderdragon death animation when it dies
do-death-animation: true

# setting this to true mutes the sound PetDragons make
silent-dragons: false

# How many SECONDS a player has to wait before his dragon can shoot again
# Keep it as a double so 2.0 instead of 2 !
shoot-cooldown-seconds: 2.0

# Control how fast a dragon can fly. Default is one, which is approximately 1 block per tick (20 blocks/second). 
# Setting this to to zero, negatives or really high numbers might have unexpected consequences!
# Keep it as a double so 1.0 instead of 1 !
speed-multiplier: 1.0

# Maximum amount of dragons a player can spawn, all worlds combined (only counts loaded worlds)
# V1.4 Spawn eggs ignore this setting, so that is another way to control PetDragon amount (e.g. by giving 1 egg per player)
# Players with permission 'petdragon.bypass.dragonlimit' will ignore this
max-dragons-per-player: 3

# Whether or not clicking on the located-a-dragon message will remove that dragon
# ONLY enable if server uses Spigot or Paper (or any of their forks)!
click-to-remove: false

# This name will be given to the PetDragon spawn egg (obtainable via /dragon egg)
dragon-egg-name: "§5§lPetDragon spawn egg"

# Whether PetDragon spawn eggs will be used up even in gamemodes like creative
always-use-up-egg: true

messages:
   no-command-permission: "§l§cSorry§r§7, you don't have permission to use that command!"
   no-ride-permission: "§l§cSorry§r§7, you don't have permission to ride dragons!"
   # you can use {owner} for the name of the person who spawned/owns this dragon
   no-joyride-permission: "§l§cSorry§r§7, you can't ride {owner}'s dragon!"

   # Shown when a player tries to USE a spawn egg without permission
   no-egg-permission: "§l§cSorry§r§7, you don't have permission to use §5§lPetDragon§r§7 spawn eggs!"

   # Shown when you receive a dragon spawn egg through command
   egg-received: "You have been given a §5§lPetDragon§r spawn egg!"
   egg-hatched: "§aThe egg hatched! A new §5§lPetDragon§r§a has been spawned above you!"
   
   reload-success: "§aThe plugin has been successfully reloaded!"
   reload-fail: "§cReloading the configuration failed! See the console for more details."
   
   command-usage: "§6USAGE    §r/dragon §7<spawn | locate | remove | egg>"

   dragon-spawned: "§aA new §5§lPetDragon§r§a has been spawned above you!"

   # you can use {amount} here which will be replaced with max amount you configured above!
   too-many-dragons: "§cYou have too many dragons, remove one first. The maximum amount is {amount}!"
   
   dragon-removed: "Dragon succesfully removed"
   no-dragon-found-to-remove: "§7No dragon found to remove, make sure you are really close to it!"
   remove-range-invalid: "§cPlease specify the range as a positive integer smaller than 20"
   # you can use {owner} for the name of the person who spawned/owns this dragon
   not-yours-to-remove: "§cYou are not allowed to remove {owner}'s dragon!"
   
   locate-no-dragons: "§7You don't seem to have any dragons yet, spawn them using §5/dragon spawn"
   # {amount} will be replaced with the amount of dragons a player has
   located-dragons-header: "§aYou currently have {amount} registered dragon(s)! These are loaded:"
   # {x} {y} and {z} will be replaced with coordinates. {world} with world-name
   located-a-dragon: "§7--> {x}, {y}, {z} in world '{world}'" 
   # only applies when click-to-remove flag above is set to 'true'
   located-hover-text: "§aClick to remove!"

