# The config of the PetDragon plugin
# Created by 3ricL, minecraft name: Ericdebouwer
# -
# Edit this configuration with care, and NEVER use tabs!
# If this configuration breaks, my plugin will try to explain what should be changed/fixed
# to reset it, simply remove it from the "PetDragon" folder and it will generate a new one
# -
# You can use color codes in the messages by using the §-symbol,
# as seen on: https://www.digminecraft.com/lists/color_list_pc.php
###################################################################

plugin-prefix: "§r[§5§lPetDragon§r] "

# Whether or not using a mouse button with empty hand allows you to ride a dragon
# Both can be enabled at the same time
right-click-to-ride: true
left-click-to-ride: true

messages:
   no-command-permission: "§l§cSorry§r§7, you don't have permission to use that command!"
   no-ride-permission: "§l§cSorry§r§7, you don't have permission to ride dragons!"
   
   command-usage: "§6USAGE    §r/dragon §7<spawn | remove>"
   
   dragon-spawned: "§aA new §5§lPetDragon§r§a has been spawned above you!"
   dragon-removed: "Dragon succesfully removed"
   no-dragon-found-to-remove: "§7No dragon found to remove, make sure you are really close to it!"

