main: com.ericdebouwer.petdragon.PetDragon
version: 1.2
api-version: 1.14
name: PetDragon
author: ericdebouwer (3ricL)
commands: 
    dragon:
permissions:
   petdragon.command.spawn:
      default: op
   petdragon.command.remove:
      default: op
   petdragon.command.locate:
      default: true
   petdragon.command.reload:
      default: op
   petdragon.bypass.dragonlimit:
      default: op
   petdragon.ride:
      default: true
   petdragon.shoot:
      default: true