main: com.ericdebouwer.petdragon.PetDragon
version: 1.3.2
load: STARTUP
api-version: 1.14
name: PetDragon
author: ericdebouwer (3ricL)
commands: 
    dragon:
permissions:
   petdragon.command.spawn:
      default: op
   petdragon.command.remove:
      default: op
   petdragon.command.locate:
      default: true
   petdragon.command.reload:
      default: op
   petdragon.bypass.dragonlimit:
      default: op
   petdragon.bypass.owner:
      default: op
   petdragon.hurt.self:
      default: true
   petdragon.hurt.others:
      default: op
   petdragon.ride:
      default: true
   petdragon.shoot:
      default: true