main: com.ericdebouwer.petdragon.PetDragon
version: ${project.version}
load: STARTUP
api-version: 1.14
description: Fly custom fully controllable EnderDragons and destroy your foes!
website: https://www.spigotmc.org/resources/82744/
name: PetDragon
author: ericdebouwer (3ricL)
commands: 
    dragon:
permissions:
   petdragon.command.spawn:
      default: op
   petdragon.command.remove:
      default: op
   petdragon.command.locate:
      default: true
   petdragon.command.reload:
      default: op
   petdragon.command.egg:
      default: op
   petdragon.bypass.dragonlimit:
      default: op
   petdragon.bypass.owner:
      default: op
   petdragon.bypass.remove:
      default: op
   petdragon.hurt.self:
      default: true
   petdragon.hurt.others:
      default: op
   petdragon.spawnegg:
      default: true
   petdragon.ride:
      default: true
   petdragon.shoot:
      default: true